### ISSUE TITLE
[BUG] Some code blocks in the installation instructions are not rendering

### ISSUE THREAD

**Issue by sandeep-ps** [clowder-framework/clowder#329]
**Describe the bug**
Some code blocks in the installation instructions on the Read The Docs page are not rendering.

**To Reproduce**
1. Go to https://clowder-framework.readthedocs.io/en/latest/userguide/installing_clowder.html 
2. Scroll down to https://clowder-framework.readthedocs.io/en/latest/userguide/installing_clowder.html#expose-docker-
services-ports-to-clowder 
3. See that the code blocks are missing (see screenshot below.)

**Expected behavior**
All code blocks need to render correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/4306604/155760153-fb0f210d-ef18-49f9-8657-4967e2f8d857.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 98.0.4758.102 (Official Build) (x86_64)

**Additional context**
Relevant RST file section: https://github.com/clowder-framework/clowder/blob/develop/doc/src/sphinx/userguide/installing_clowder.rst#expose-docker-services-ports-to-clowder

**Comment by KastanDay** [comment]
As far as I can tell, this is the only code block that is missing in the HTML render.

The offending block looks like: 
``` rst
.. code:: yml

   # this lets Clowder communicate with the necessary services
   # These services (Mongo, RabbitMQ, ElsticSearch) will be run 
   # via docker containers using the command line

   services:
     mongo:
       image: mongo:3.4
       ports:
         - 27017:27017
     rabbitmq:
       image: rabbitmq:management-alpine
       ports:
         - 5672:5672
         - 15672:15672
     elasticsearch:
       image: elasticsearch:2
       ports:
         - 9200:9200
         - 9300:9300
```

Possible causes: 
* the code formatting is "yml" which [appears to be supported](https://www.sphinx-doc.org/en/1.4.9/markup/code.html), but could be the problem. We might want to switch from `.. code:: yml` to `.. code:: yaml` (or `none` or `guess`)
* The code has new lines and indents. We might want to switch from `.. code:: yml` to `.. code-block:: yaml`

I think the fix is: `.. code:: yaml` (simply spelling out 'yaml')

I will test locally, then submit a PR.

**Comment by sandeep-ps** [comment]
Good catch, @KastanDay!
